version: "3.3"
services:
  api:
    container_name: api
    restart: always
    build: .
    image: api
    environment:
      DB_NAME: feed
      DB_USER: root
      DB_PASS: root
      DB_PORT: 27017
      DB_HOST: db
      DB_CONNECTION: mongodb
    links:
      - mongodb
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - daily-trends

  mongodb:
    container_name: db
    restart: always
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    networks:
      - daily-trends

networks:
  daily-trends:
